up

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,8 +19,6 @@ jobs:
             COMPOSER_MEMORY_LIMIT: -1
             COMPOSER_FLAGS: ${{ matrix.composer_flags }}
             SYMFONY_VERSION: ${{ matrix.symfony_version }}
-        # prefer lowest gives issues with the latest "void" return type
-        continue-on-error: ${{ matrix.composer_flags }}
         steps:
             - name: Setup PHP
               uses: shivammathur/setup-php@v2
@@ -38,8 +36,12 @@ jobs:
                 COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
             - name: Run tests
               run: |
-                # TODO: we should add things like phpstan, phpcs etc
-                php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
+                # hack to make sure --prefer-lowest can fail
+                if [ "COMPOSER_FLAGS" == "--prefer-lowest"]; then
+                  php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover || true
+                else
+                  php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
+                fi
             - name: Upload coverage
               run: |
                 wget https://scrutinizer-ci.com/ocular.phar
